id: IB22A0904
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 10:42:14.134236+00:00
last_modified: 2022-12-14 10:42:14.134240+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-057-001
  eft-text-version: 1.1.5 2020
  title: Toh_142-The_Dharani_Entering_into_Non-conceptuality-v2
bases:
  72CA:
    source_metadata: null
    order: 1
    base_file: 72CA.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
